// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp1S6jnmJmTYZvcG1DbbHL3T_XPJFQp8k',
    appId: '1:307000957257:web:76715db7a748a9528ee298',
    messagingSenderId: '307000957257',
    projectId: 'safestreet-ae1b1',
    authDomain: 'safestreet-ae1b1.firebaseapp.com',
    storageBucket: 'safestreet-ae1b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApZZqVlkg_ErIjMPRsfRu3FkSZMta6sfg',
    appId: '1:307000957257:android:9a1d914f0cd11f278ee298',
    messagingSenderId: '307000957257',
    projectId: 'safestreet-ae1b1',
    storageBucket: 'safestreet-ae1b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJBZRq3qQQEzqOP3Y4JvBhhETjjuTzDjw',
    appId: '1:307000957257:ios:0bce7b554ff34a548ee298',
    messagingSenderId: '307000957257',
    projectId: 'safestreet-ae1b1',
    storageBucket: 'safestreet-ae1b1.appspot.com',
    iosBundleId: 'com.example.safeStreet',
  );
}
